### ISSUE TITLE
[swig] Error in running preinstall script 

### ISSUE THREAD

**Issue by tngan** [node-tensorflow/node-tensorflow#10]
This is a follow up with #7 and #9. Error is caught while running preinstall script.

```
> node-tensorflow@0.0.1 _preinstall /github/node-tensorflow
> git submodule update --init --recursive && ./tools/build.sh

Submodule 'lib/tensorflow' (https://github.com/tensorflow/tensorflow.git) registered for path 'lib/tensorflow'
Cloning into 'lib/tensorflow'...
remote: Counting objects: 17604, done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 17604 (delta 1), reused 0 (delta 0), pack-reused 17598
Receiving objects: 100% (17604/17604), 24.91 MiB | 310.00 KiB/s, done.
Resolving deltas: 100% (11809/11809), done.
Checking connectivity... done.
Submodule path 'lib/tensorflow': checked out 'c4207090d68151fb967672a90ea6d574e62cfba0'
Submodule 'google/protobuf' (https://github.com/google/protobuf.git) registered for path 'google/protobuf'
Cloning into 'google/protobuf'...
remote: Counting objects: 30335, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 30335 (delta 12), reused 0 (delta 0), pack-reused 30302
Receiving objects: 100% (30335/30335), 28.82 MiB | 70.00 KiB/s, done.
Resolving deltas: 100% (20280/20280), done.
Checking connectivity... done.
Submodule path 'lib/tensorflow/google/protobuf': checked out 'bc215089ca7d9da3a2b313b250d1dee665eda438'

HEAD is now at c420709 Merge pull request #1050 from chemelnucfin/fixcomparison.
patching file tensorflow/cc/BUILD
No GPU support will be enabled for TensorFlow
Configuration finished
....................................
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:11:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:12:6: First argument of load() is a path, not a label. It should start with a single slash if it is an absolute path..
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:11:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:12:6: file '/tensorflow:tensorflow.bzl.bzl' was not correctly loaded. Make sure the 'load' statement appears in the global scope in your file.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:21:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 14
        cc_library(name = "cc_op_gen_main", srcs = ["ops/cc_op_gen.cc", "ops/cc_op_gen_main.cc"], hdrs = ["ops/cc_op_gen.h"], copts = tf_copts(), deps = ["//tensorflow/core:framework"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 21, in cc_library
        tf_copts
name 'tf_copts' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:28:1: name 'tf_gen_op_wrappers_cc' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:66:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 63
        cc_binary(name = "tutorials_example_trainer", srcs = ["tutorials/example_trainer.cc"], copts = tf_copts(), linkopts = ["-lpthread", "-lm"], deps = [":cc_ops", "//tensorflow/core:all_kernels", "//tensorflow/core:tensorflow"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 66, in cc_binary
        tf_copts
name 'tf_copts' is not defined.
ERROR: /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD:80:13: Traceback (most recent call last):
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 78
        cc_binary(name = "libtensorflow.so", copts = tf_copts(), linkshared = 1, linkopts = ["-lpthread", "-lm"], deps = [":cc_ops", "//tensorflow/core:all_kernels", "//tensorflow/core:tensorflow"])
    File "/github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD", line 80, in cc_binary
        tf_copts
name 'tf_copts' is not defined.
ERROR: no such target '//tensorflow/cc:libtensorflow.so': target 'libtensorflow.so' not declared in package 'tensorflow/cc' defined by /github/node-tensorflow/lib/tensorflow/tensorflow/cc/BUILD.
INFO: Elapsed time: 1.973s
```

**Comment by peterbraden** [comment]
Can you leave:
- The version of Bazel you have
- Your OS / Version
- The version of compiler you have

Thanks

**Comment by tngan** [comment]
- Bazel version

```
Build label: 0.1.1
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/bazel-main_deploy.jar
Build time: Thu Oct 15 20:51:11 2015 (1444942271)
Build timestamp: 1444942271
Build timestamp as int: 1444942271
```
- OS / Version 

```
OS X El Capitan‎ 10.11.3
```
- g++ -v

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin15.3.0
Thread model: posix
```

**Comment by tngan** [comment]
The error still exists but I can still run through `npm install` and `npm test` locally after `npm run _preinstall`.

**Comment by tngan** [comment]
Currently it's okay for the latest build.

```
Build label: 0.2.1-homebrew
Build target: bazel-out/local_darwin-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Apr 1 00:35:17 2016 (1459470917)
Build timestamp: 1459470917
Build timestamp as int: 1459470917
```
